/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

Object.defineProperty(exports, "__esModule", { value: true });
module.exports = require('../../../../../has-own-property/bit.utils/1.0.0/src/object/hasOwnProperty');