/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

module.exports = require('../../components/.dependencies/internal/babel-base-compiler/bit.envs/1.0.1/babelBaseCompiler/index');